// <auto-generated />
using System;
using IronGate.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronGate.Core.Persistence.Migrations
{
    [DbContext(typeof(IronGateDbContext))]
    [Migration("20251127205432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronGate.Core.Database.Entities.DefenseProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxAttemptsPerMinute")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("UseCaptcha")
                        .HasColumnType("bit");

                    b.Property<bool>("UsePepper")
                        .HasColumnType("bit");

                    b.Property<bool>("UseRateLimiting")
                        .HasColumnType("bit");

                    b.Property<bool>("UseTotp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("defense_profiles", (string)null);
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.ExperimentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AttemptsPerSecond")
                        .HasColumnType("float");

                    b.Property<double>("AverageLatencyMs")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DefenseProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<Guid>("HashProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<double?>("TimeToFirstSuccessMs")
                        .HasColumnType("float");

                    b.Property<long>("TotalAttempts")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DefenseProfileId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("HashProfileId", "DefenseProfileId");

                    b.ToTable("experiment_runs", (string)null);
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.HashProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Algorithm")
                        .HasColumnType("int");

                    b.Property<int?>("Iterations")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryKb")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Parallelism")
                        .HasColumnType("int");

                    b.Property<int>("PepperMode")
                        .HasColumnType("int");

                    b.Property<int>("SaltMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("hash_profiles", (string)null);
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Argon2Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Argon2Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BcryptHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BcryptSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sha256Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.ExperimentRun", b =>
                {
                    b.HasOne("IronGate.Core.Database.Entities.DefenseProfile", "DefenseProfile")
                        .WithMany("ExperimentRuns")
                        .HasForeignKey("DefenseProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IronGate.Core.Database.Entities.HashProfile", "HashProfile")
                        .WithMany("ExperimentRuns")
                        .HasForeignKey("HashProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IronGate.Core.Database.Entities.User", "User")
                        .WithMany("ExperimentRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenseProfile");

                    b.Navigation("HashProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.DefenseProfile", b =>
                {
                    b.Navigation("ExperimentRuns");
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.HashProfile", b =>
                {
                    b.Navigation("ExperimentRuns");
                });

            modelBuilder.Entity("IronGate.Core.Database.Entities.User", b =>
                {
                    b.Navigation("ExperimentRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
